name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - lts/hydrogen # 18
          - lts/iron # 20
          - current

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          check-latest: true
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run linters
        run: npm run lint

      - name: Run TS check
        run: npx tsc --noEmit

      - name: Run tests
        run: npm run test
